import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//components
import Header from "../components/Header";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Home Movies And Series</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <main>
            <section>
                Content
            </section>
            <h1 className="text-3xl font-bold underline">
                Hello World
            </h1>
        </main>
        <Footer/>
    </div>
  )
}

export default Home
